# This is a basic workflow to help you get started with Actions

name: Auto Deploy Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "main"
      

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Folder: build
  #Deployment Branch
  Branch: Build

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    concurrency: ci-${{ github.ref }}  # Recommended if you intend to make multiple deployments in quick succession.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install & Build
        run: cd docusaurus-site && npm install && npm install --save @easyops-cn/docusaurus-search-local && npm run build
        
    #cd docusaurus-site && GIT_USER=${{ github.actor }} GIT_PASS=${{ secrets.GITHUB_TOKEN }} yarn deploy
    #/usr/bin/
        
      - name: Deploy
        run: |
          npm install --global yarn
          git config user.name "${{ github.actor }}"
          git config user.email "niranjan.m2199@gmail.com" 
          git remote rm origin
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch --no-recurse-submodules --depth=1 origin  ${{ env.Branch }}
          git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
          git checkout -B Build origin/Buildgit checkout -B ${{ env.Branch }} origin/${{ env.Branch }}
          chmod -R +rw /home/runner/work/test-docusaurus-2/test-docusaurus-2/docusaurus-site/build
          rsync -q -av --checksum --progress /home/runner/work/test-docusaurus-2/test-docusaurus-2/docusaurus-site/build/. github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .ssh --exclude .git --exclude .github
          git add --all .
          git push --force https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git Build
          chmod -R +rw github-pages-deploy-action-temp-deployment-folder
          git worktree remove github-pages-deploy-action-temp-deployment-folder --force
          
