# This is a basic workflow to help you get started with Actions

name: Auto Deploy Github pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "main"     

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    concurrency: ci-${{ github.ref }}  # Recommended if you intend to make multiple deployments in quick succession.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./docusaurus-site
    
    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          path: ./docusaurus-site
        
      - name: Install dependencies
        run: npm ci && npm install --save @easyops-cn/docusaurus-search-local
        
      - name: Build website
        run: npm run build
        
    #cd docusaurus-site && GIT_USER=${{ github.actor }} GIT_PASS=${{ secrets.GITHUB_TOKEN }} yarn deploy
    #/usr/bin/
        
     # - name: Deploy to GitHub Pages
     #   uses: peaceiris/actions-gh-pages@v3
     #   with:
     #     github_token: ${{ secrets.GITHUB_TOKEN }}
     #     # Build output to publish to the `gh-pages` branch:
     #    publish_dir: docusaurus-site/build
     #     publish_branch: deployment-branch
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
     #     user_name: ${{ github.actor }}
     #     user_email: 41898282+github-actions[bot]@users.noreply.github.com
    
      - name: Deploy
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          GIT_USER=${{ github.actor }} GIT_PASS=${{ secrets.GITHUB_TOKEN }} yarn deploy
